---
generic-service:
  nameOverride: ppud-replacement-bandiera

  replicaCount: 2

  image:
    repository: docker.io/dazoakley/bandiera
    tag: 4.0.3
    port: 5000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 2000

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: bandiera-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Bandiera'
    # which cluster are we on: live-1 is blue, live is green
    contextColour: green


  livenessProbe:
    httpGet:
      path: /status/live

  readinessProbe:
    httpGet:
      path: /status/ready

  # Environment variables to load into the deployment
  env: {}
    # SENTRY_DSN:

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    bandiera-database:
      DATABASE_URL: DATABASE_URL

generic-prometheus-alerts:
  targetApplication: ppud-replacement-bandiera
